#### Accessing/Changing specific elements,rows,columns,etc

In [200]:
import numpy as np
from io import StringIO
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [201]:
# Get a specific element [row,col] uses index
a[1,5]


13

In [202]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [203]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [204]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [205]:
# Changes values inside array with index
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [206]:
#3-dimensional Array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [207]:
#Get Specific element (work outside in)
b[:,:,1]



array([[2, 4],
       [6, 8]])

In [208]:
# replace
b[:,1,:]= [[2,3],[9,10]]

In [209]:
b

array([[[ 1,  2],
        [ 2,  3]],

       [[ 5,  6],
        [ 9, 10]]])

### Initializing Different Types of Arrays

In [210]:
# initialize All 0s Matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [211]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [212]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [213]:
# Any other number (full_like)
np.full_like(a ,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [214]:
# Random decimal numbers
np.random.rand(4,3,3)

array([[[0.15452722, 0.7888994 , 0.23683941],
        [0.54238398, 0.88279992, 0.31827939],
        [0.72037349, 0.67666214, 0.47308213]],

       [[0.375827  , 0.0898474 , 0.86036834],
        [0.19225492, 0.47311286, 0.35190574],
        [0.637462  , 0.78405132, 0.79023621]],

       [[0.2128041 , 0.21996226, 0.1194762 ],
        [0.70513918, 0.40064052, 0.77714405],
        [0.76274218, 0.11459408, 0.63770322]],

       [[0.41981004, 0.38047732, 0.76128704],
        [0.81607699, 0.95805783, 0.94020063],
        [0.15977582, 0.14505259, 0.39573171]]])

In [215]:
np.random.random_sample(b.shape)

array([[[0.35870614, 0.11817599],
        [0.34693077, 0.55541621]],

       [[0.20450019, 0.80820812],
        [0.85813249, 0.00331431]]])

In [216]:
np.random.rand(a.shape[0], b.shape[1], b.shape[2])

array([[[0.53535723, 0.29107443],
        [0.02688237, 0.28636626]],

       [[0.11649126, 0.67106605],
        [0.43346687, 0.28677594]]])

In [217]:
# Random Integer Values
np.random.randint(-2,7, size=(3,3,3))

array([[[-2,  5, -1],
        [ 3, -1,  2],
        [ 3,  4,  0]],

       [[-2,  2, -1],
        [ 2,  5,  0],
        [ 3,  2,  5]],

       [[ 5,  2,  0],
        [ 0, -1, -1],
        [-2,  2,  6]]])

In [218]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [219]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [220]:
# Fill in a matriks array into another array

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying Arrays!!!

In [221]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 100

print(a)

[1 2 3]


#### Mathematics

In [222]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [223]:
a + 2

array([3, 4, 5, 6])

In [224]:
a - 2

array([-1,  0,  1,  2])

In [225]:
a * 2

array([2, 4, 6, 8])

In [226]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [227]:
a % 2 

array([1, 0, 1, 0], dtype=int32)

In [228]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [229]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [230]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra

In [231]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

cs = np.full((2,2),3)
print(c)

b[1:3,0:2] = cs
print(b)

np.matmul(b,cs)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 2]
 [3 3]
 [3 3]]


array([[12, 12],
       [18, 18],
       [18, 18]])

In [232]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [233]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [234]:
np.min(stats, axis=1)

array([1, 4])

In [235]:
np.max(stats,axis=1)

array([3, 6])

In [236]:
np.sum(stats)

21

#### Reorganizing Arrays

In [237]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [238]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [239]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
Load Data from File

In [242]:
np.genfromtxt("datad.txt", delimiter=',')


OSError: datad.txt not found.