In [1]:
import numpy as np

In [26]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
b.ndim

2

In [13]:
# Get Shape
b.shape

(2, 3)

In [17]:
# Get Type
a.dtype

dtype('int16')

In [29]:
# Get Size
a.itemsize
b.itemsize

8

In [30]:
# Get Total Size
b.nbytes

48